[theme]
base = "light"
primaryColor = "#1467b6"
backgroundColor = "#f5f0e6"
secondaryBackgroundColor = "#ece5d3"
textColor = "#1c1914"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
